
local sortordermenus = {
	container = {
						{"wooden-chest"						,"shinybob-chests1"				,"a1"},
						{"iron-chest"							,"shinybob-chests1"				,"a2"},
						{"steel-chest"							,"shinybob-chests1"				,"a3"},
						{"brass-chest"							,"shinybob-chests1"				,"a4"},
						{"titanium-chest"						,"shinybob-chests1"				,"a5"},
						{"tungsten-chest"						,"shinybob-chests1"				,"a6"},
						{"storehouse-basic"						,"shinybob-chests1"				,"a7"},
						{"warehouse-basic"						,"shinybob-chests1"				,"a8"},
						},

	transportbelt = {
						{"transport-belt"						,"shinybob-belts"				,"a1"},
						{"fast-transport-belt"					,"shinybob-belts"				,"a2"},
						{"express-transport-belt"				,"shinybob-belts"				,"a3"},
						{"green-transport-belt"					,"shinybob-belts"				,"a4"},
						{"purple-transport-belt"					,"shinybob-belts"				,"a5"},
						},

	undergroundbelt = {
						{"underground-belt"						,"shinybob-underground-belts"		,"a1"},
						{"fast-underground-belt"					,"shinybob-underground-belts"		,"a2"},
						{"express-underground-belt"				,"shinybob-underground-belts"		,"a3"},
						{"green-underground-belt"				,"shinybob-underground-belts"		,"a4"},
						{"purple-underground-belt"				,"shinybob-underground-belts"		,"a5"},
						},

	splitter = {
						{"splitter"							,"shinybob-splitters"			,"a1"},
						{"fast-splitter"						,"shinybob-splitters"			,"a2"},
						{"express-splitter"						,"shinybob-splitters"			,"a3"},
						{"green-splitter"						,"shinybob-splitters"			,"a4"},
						{"purple-splitter"						,"shinybob-splitters"			,"a5"},
						{"single-splitter"						,"shinybob-splitters"			,"a9"},
						},

	hackedsplitter = {
						{"hacked-splitter"						,"shinybob-splitters"			,"b1"},
						{"hacked-fast-splitter"					,"shinybob-splitters"			,"b2"},
						{"hacked-express-splitter"				,"shinybob-splitters"			,"b3"},
						{"hacked-green-splitter"					,"shinybob-splitters"			,"b4"},
						{"hacked-purple-splitter"				,"shinybob-splitters"			,"b5"},
						},

	loader = {
						{"loader"								,"shinybob-loader"				,"a1"},
						{"fast-loader"							,"shinybob-loader"				,"a2"},
						{"express-loader"						,"shinybob-loader"				,"a3"},
						{"green-loader"						,"shinybob-loader"				,"a4"},
						{"purple-loader"						,"shinybob-loader"				,"a5"},
						},
	miniloader = {
						{"miniloader"							,"shinybob-loader"				,"b1"},
						{"fast-miniloader"						,"shinybob-loader"				,"b2"},
						{"express-miniloader"					,"shinybob-loader"				,"b3"},
						{"green-miniloader"						,"shinybob-loader"				,"b4"},
						{"purple-miniloader"					,"shinybob-loader"				,"b5"},
						},

	beltsorter = {
						{"belt-sorter1"						,"shinybob-beltsorter"			,"a1"},
						{"belt-sorter2"						,"shinybob-beltsorter"			,"a2"},
						{"belt-sorter3"						,"shinybob-beltsorter"			,"a3"},
						{"belt-sorter4"						,"shinybob-beltsorter"			,"a4"},
						{"belt-sorter5"						,"shinybob-beltsorter"			,"a5"},
						
						{"filter-miniloader"					,"shinybob-beltsorter"			,"b1"},
						{"fast-filter-miniloader"				,"shinybob-beltsorter"			,"b2"},
						{"express-filter-miniloader"				,"shinybob-beltsorter"			,"b3"},
						{"green-filter-miniloader"				,"shinybob-beltsorter"			,"b4"},
						{"purple-filter-miniloader"				,"shinybob-beltsorter"			,"b5"},
						},

	inserter = {
						{"burner-inserter"						,"shinybob-inserter"			,"a1"},
						{"inserter"							,"shinybob-inserter"			,"a2"},
						{"long-handed-inserter"					,"shinybob-inserter"			,"a3"},

						{"fast-inserter"						,"shinybob-fast-inserter"		,"a1"},
						{"express-inserter"						,"shinybob-fast-inserter"		,"a2"},
						{"filter-inserter"						,"shinybob-fast-inserter"		,"a3"},
						{"express-filter-inserter"				,"shinybob-fast-inserter"		,"a4"},

						{"stack-inserter"						,"shinybob-stack-inserter"		,"a1"},
						{"express-stack-inserter"				,"shinybob-stack-inserter"		,"a2"},
						{"stack-filter-inserter"					,"shinybob-stack-inserter"		,"a3"},
						{"express-stack-filter-inserter"			,"shinybob-stack-inserter"		,"a4"},
						},


	electricpole = {
						{"medium-electric-pole"					,"shinybob-energy-poles"			,"a1"},
						{"medium-electric-pole-2"				,"shinybob-energy-poles"			,"a2"},
						{"medium-electric-pole-3"				,"shinybob-energy-poles"			,"a3"},
						{"medium-electric-pole-4"				,"shinybob-energy-poles"			,"a4"},

						{"big-electric-pole"					,"shinybob-energy-poles"			,"b1"},
						{"big-electric-pole-2"					,"shinybob-energy-poles"			,"b2"},
						{"big-electric-pole-3"					,"shinybob-energy-poles"			,"b3"},
						{"big-electric-pole-4"					,"shinybob-energy-poles"			,"b4"},

						{"small-electric-pole"					,"shinybob-energy-poles"			,"b5"},

						{"substation"							,"shinybob-energy-substation"		,"a2"},
						{"substation-2"						,"shinybob-energy-substation"		,"a3"},
						{"substation-3"						,"shinybob-energy-substation"		,"a4"},
						{"substation-4"						,"shinybob-energy-substation"		,"a5"},
						},										

	railsignaltrainstop = {
						{"rail"								,"shinybob-rails"				,"a1"},
						{"straight-rail"						,"shinybob-rails"				,"a2"},
						{"train-stop"							,"shinybob-rails"				,"b1"},
						{"smart-train-stop"						,"shinybob-rails"				,"b2"},
						{"logistic-train-stop"					,"shinybob-rails"				,"b3"},
						{"rail-signal"							,"shinybob-rails"				,"c1"},
						{"rail-chain-signal"					,"shinybob-rails"				,"c2"},
						{"train-limit"							,"shinybob-rails"				,"d1"},
						{"train-unlimit"						,"shinybob-rails"				,"d2"},
						},

	locomotive = {
						{"locomotive"							,"shinybob-trains"				,"a1"},				  
						{"bob-locomotive-2"						,"shinybob-trains"				,"a2"},				  
						{"bob-locomotive-3"						,"shinybob-trains"				,"a3"},				  
						{"bob-armoured-locomotive"				,"shinybob-trains"				,"a4"},				  
						{"bob-armoured-locomotive-2"				,"shinybob-trains"				,"a5"},				  
						{"artillery-wagon"						,"shinybob-trains"				,"a6"},				  
						{"bob-artillery-wagon-2"					,"shinybob-trains"				,"a7"},				  
						{"bob-artillery-wagon-3"					,"shinybob-trains"				,"a8"},				  
						{"shuttleTrain"						,"shinybob-trains"				,"b1"},				  
						{"farl"								,"shinybob-trains"				,"b2"},				  
						{"farl-roboport"						,"shinybob-trains"				,"b3"},				  
						{"shuttle-lite"						,"shinybob-trains"				,"b4"},				  
						{"crawler-locomotive"					,"shinybob-trains"				,"b5"},				  
						{"crawler-locomotive-wagon"				,"shinybob-trains"				,"b6"},				  
						},						

	cargowagon = {
						{"cargo-wagon"							,"shinybob-wagons1"				,"a1"},
						{"bob-cargo-wagon-2"					,"shinybob-wagons1"				,"a2"},
						{"bob-cargo-wagon-3"					,"shinybob-wagons1"				,"a3"},
						{"bob-armoured-cargo-wagon"				,"shinybob-wagons1"				,"a4"},
						{"bob-armoured-cargo-wagon-2"				,"shinybob-wagons1"				,"a5"},
						},

	fluidwagon = {
						{"fluid-wagon"							,"shinybob-wagons2"				,"b1"},
						{"bob-fluid-wagon-2"					,"shinybob-wagons2"				,"b2"},
						{"bob-fluid-wagon-3"					,"shinybob-wagons2"				,"b3"},
						{"bob-armoured-fluid-wagon"				,"shinybob-wagons2"				,"b4"},
						{"bob-armoured-fluid-wagon-2"				,"shinybob-wagons2"				,"b5"},
						},		

	car = {
						{"car"								,"shinybob-wagons2"				,"c1"},
						{"tank"								,"shinybob-wagons1"				,"d1"},
						{"bob-tank-2"							,"shinybob-wagons1"				,"d2"},
						{"bob-tank-3"							,"shinybob-wagons1"				,"d3"},
						{"gunship"							,"shinybob-cars-tanks"			,"e1"},
						{"jet"								,"shinybob-cars-tanks"			,"e2"},
						{"cargo-plane"							,"shinybob-cars-tanks"			,"e3"},
						{"flying-fortress"						,"shinybob-cars-tanks"			,"e4"},
						},
						
	logisticcontainer = {
						{"logistic-chest-storage"				,"shinybob-network-storage1"		,"a1"},
						{"logistic-chest-passive-provider"			,"shinybob-network-storage1"		,"a2"},
						{"logistic-chest-requester"				,"shinybob-network-storage1"		,"a3"},
						{"logistic-chest-active-provider"			,"shinybob-network-storage1"		,"a4"},
						{"logistic-chest-buffer"					,"shinybob-network-storage1"		,"a5"},
						{"logistic-chest-titanium-storage"			,"shinybob-network-storage1"		,"a6"},
						{"logistic-chest-tungsten-storage"			,"shinybob-network-storage1"		,"a7"},
						{"logistic-chest-botUpgrader"				,"shinybob-network-storage1"		,"a8"},

						{"logistic-chest-storage-2"				,"shinybob-network-storage2"		,"b1"},
						{"logistic-chest-passive-provider-2"		,"shinybob-network-storage2"		,"b2"},
						{"logistic-chest-requester-2"				,"shinybob-network-storage2"		,"b3"},
						{"logistic-chest-active-provider-2"		,"shinybob-network-storage2"		,"b4"},
						{"logistic-chest-buffer-2"				,"shinybob-network-storage2"		,"b5"},
																				 
						{"logistic-chest-storage-3"				,"shinybob-network-storage3"		,"c1"},
						{"logistic-chest-passive-provider-3"		,"shinybob-network-storage3"		,"c2"},
						{"logistic-chest-requester-3"				,"shinybob-network-storage3"		,"c3"},
						{"logistic-chest-active-provider-3"		,"shinybob-network-storage3"		,"c4"},
						{"logistic-chest-buffer-3"				,"shinybob-network-storage3"		,"c5"},

						{"storehouse-storage"					,"shinybob-network-storage4"		,"d1"},
						{"storehouse-passive-provider"			,"shinybob-network-storage4"		,"d2"},
						{"storehouse-requester"					,"shinybob-network-storage4"		,"d3"},
						{"storehouse-active-provider"				,"shinybob-network-storage4"		,"d4"},
						{"storehouse-buffer"					,"shinybob-network-storage4"		,"d5"},

						{"warehouse-storage"					,"shinybob-network-storage5"		,"e1"},
						{"warehouse-passive-provider"				,"shinybob-network-storage5"		,"e2"},
						{"warehouse-requester"					,"shinybob-network-storage5"		,"e3"},
						{"warehouse-active-provider"				,"shinybob-network-storage5"		,"e4"},
						{"warehouse-buffer"						,"shinybob-network-storage5"		,"e5"},
						
						},


	circuitnetwork = {
						{"small-lamp"							,"shinybob-circuit-network"		,"a0"},
						{"arithmetic-combinator"					,"shinybob-circuit-network"		,"a1"},
						{"decider-combinator"					,"shinybob-circuit-network"		,"a2"},
						{"constant-combinator"					,"shinybob-circuit-network"		,"a3"},
						{"power-switch"						,"shinybob-circuit-network"		,"a4"},
						{"programmable-speaker"					,"shinybob-circuit-network"		,"a5"},
						{"roboport-interface"					,"shinybob-circuit-network"		,"a6"},
						},


--- =======

	storagetank = {
						{"storage-tank"						,"shinybob-storage-tank"			,"a1"},
						{"storage-tank-2"						,"shinybob-storage-tank"			,"a2"},
						{"storage-tank-3"						,"shinybob-storage-tank"			,"a3"},
						{"storage-tank-4"						,"shinybob-storage-tank"			,"a4"},

						{"bob-valve"							,"shinybob-storage-tank"			,"b1"},
						{"vent-stack"							,"shinybob-storage-tank"			,"b2"},
						{"flare-stack"							,"shinybob-storage-tank"			,"b3"},
						{"incinerator"							,"shinybob-storage-tank"			,"b4"},
						{"electric-incinerator"					,"shinybob-storage-tank"			,"b5"},
						},

	pumps = {
						{"pump"								,"shinybob-pump1"				,"a1"},
						{"bob-pump-2"							,"shinybob-pump1"				,"a2"},
						{"bob-pump-3"							,"shinybob-pump1"				,"a3"},
						{"bob-pump-4"							,"shinybob-pump1"				,"a4"},

						{"check-valve"							,"shinybob-pump1"				,"b1"},
						{"overflow-valve"						,"shinybob-pump1"				,"b2"},
						{"underflow-valve"						,"shinybob-pump1"				,"b3"},
						{"pipe-elbow"							,"shinybob-pump1"				,"b4"},
						{"pipe-junction"						,"shinybob-pump1"				,"b5"},
						{"pipe-straight"						,"shinybob-pump1"				,"b6"},

						{"offshore-pump"						,"shinybob-pump2"				,"a1"},		
						{"air-pump"							,"shinybob-pump2"				,"a2"},		
						{"air-pump-2"							,"shinybob-pump2"				,"a3"},		
						{"air-pump-3"							,"shinybob-pump2"				,"a4"},		
						{"air-pump-4"							,"shinybob-pump2"				,"a5"},		

						{"water-pump"							,"shinybob-pump2"				,"b1"},			   
						{"water-pump-2"						,"shinybob-pump2"				,"b2"},			   
						{"water-pump-3"						,"shinybob-pump2"				,"b3"},			   
						{"water-pump-4"						,"shinybob-pump2"				,"b4"},						
						{"void-pump"							,"shinybob-pump2"				,"b5"},			   
						},



	robotparts = {
						{"flying-robot-frame"					,"shinybob-robots-frame"			,"a1"},
						{"flying-robot-frame-2"					,"shinybob-robots-frame"			,"a2"},
						{"flying-robot-frame-3"					,"shinybob-robots-frame"			,"a3"},
						{"flying-robot-frame-4"					,"shinybob-robots-frame"			,"a4"},

						{"robot-brain-construction"				,"shinybob-robots-brains"		,"a1"},
						{"robot-brain-construction-2"				,"shinybob-robots-brains"		,"a2"},
						{"robot-brain-construction-3"				,"shinybob-robots-brains"		,"a3"},
						{"robot-brain-construction-4"				,"shinybob-robots-brains"		,"a4"},

						{"robot-brain-logistic"					,"shinybob-robots-brains"		,"b1"},
						{"robot-brain-logistic-2"				,"shinybob-robots-brains"		,"b2"},
						{"robot-brain-logistic-3"				,"shinybob-robots-brains"		,"b3"},
						{"robot-brain-logistic-4"				,"shinybob-robots-brains"		,"b4"},

						{"robot-tool-construction"				,"shinybob-robots-tools"			,"a1"},
						{"robot-tool-construction-2"				,"shinybob-robots-tools"			,"a2"},
						{"robot-tool-construction-3"				,"shinybob-robots-tools"			,"a3"},
						{"robot-tool-construction-4"				,"shinybob-robots-tools"			,"a4"},

						{"robot-tool-logistic"					,"shinybob-robots-tools"			,"b1"},
						{"robot-tool-logistic-2"					,"shinybob-robots-tools"			,"b2"},
						{"robot-tool-logistic-3"					,"shinybob-robots-tools"			,"b3"},
						{"robot-tool-logistic-4"					,"shinybob-robots-tools"			,"b4"},						
						},


	constructionrobot = {
						{"construction-robot"					,"shinybob-logistic-robots"		,"a1"},
						{"bob-construction-robot-2"				,"shinybob-logistic-robots"		,"a2"},
						{"bob-construction-robot-3"				,"shinybob-logistic-robots"		,"a3"},
						{"bob-construction-robot-4"				,"shinybob-logistic-robots"		,"a4"},
						{"bob-construction-robot-5"				,"shinybob-logistic-robots"		,"c1"},
						},

	logisticrobot = {
						{"logistic-robot"						,"shinybob-logistic-robots"		,"b1"},
						{"bob-logistic-robot-2"					,"shinybob-logistic-robots"		,"b2"},
						{"bob-logistic-robot-3"					,"shinybob-logistic-robots"		,"b3"},
						{"bob-logistic-robot-4"					,"shinybob-logistic-robots"		,"b4"},
						{"bob-logistic-robot-5"					,"shinybob-logistic-robots"		,"d1"},
						},

	roboportparts = {
						{"roboport-antenna-1"					,"shinybob-roboport-parts1"		,"a1"},
						{"roboport-antenna-2"					,"shinybob-roboport-parts1"		,"a2"},
						{"roboport-antenna-3"					,"shinybob-roboport-parts1"		,"a3"},
						{"roboport-antenna-4"					,"shinybob-roboport-parts1"		,"a4"},
						{"roboport-chargepad-1"					,"shinybob-roboport-parts1"		,"b1"},
						{"roboport-chargepad-2"					,"shinybob-roboport-parts1"		,"b2"},
						{"roboport-chargepad-3"					,"shinybob-roboport-parts1"		,"b3"},
						{"roboport-chargepad-4"					,"shinybob-roboport-parts1"		,"b4"},

						{"bob-logistic-zone-expander" 			,"shinybob-roboport-parts2"		,"a1"},
						{"bob-logistic-zone-expander-2"			,"shinybob-roboport-parts2"		,"a2"},
						{"bob-logistic-zone-expander-3"			,"shinybob-roboport-parts2"		,"a3"},
						{"bob-logistic-zone-expander-4"			,"shinybob-roboport-parts2"		,"a4"},
						{"bob-robo-charge-port"  				,"shinybob-roboport-parts2"		,"b1"},
						{"bob-robo-charge-port-2"				,"shinybob-roboport-parts2"		,"b2"},
						{"bob-robo-charge-port-3"				,"shinybob-roboport-parts2"		,"b3"},
						{"bob-robo-charge-port-4"				,"shinybob-roboport-parts2"		,"b4"},
						},
	roboport = {

						{"roboport-door-1"						,"shinybob-roboports"			,"a1"},
						{"roboport-door-2"						,"shinybob-roboports"			,"a2"},
						{"roboport-door-3"						,"shinybob-roboports"			,"a3"},
						{"roboport-door-4"						,"shinybob-roboports"			,"a4"},

						{"bob-robo-charge-port-large"				,"shinybob-roboports"			,"b1"},
						{"bob-robo-charge-port-large-2"			,"shinybob-roboports"			,"b2"},
						{"bob-robo-charge-port-large-3"			,"shinybob-roboports"			,"b3"},
						{"bob-robo-charge-port-large-4"			,"shinybob-roboports"			,"b4"},

						{"bob-robochest"						,"shinybob-expander"			,"a1"},
						{"bob-robochest-2"						,"shinybob-expander"			,"a2"},
						{"bob-robochest-3"						,"shinybob-expander"			,"a3"},
						{"bob-robochest-4"						,"shinybob-expander"			,"a4"},

						{"roboport"							,"shinybob-expander"			,"b1"},
						{"bob-roboport-2"						,"shinybob-expander"			,"b2"},
						{"bob-roboport-3"						,"shinybob-expander"			,"b3"},
						{"bob-roboport-4"						,"shinybob-expander"			,"b4"},

						{"bob-logistic-zone-interface"			,"shinybob-roboport-extras"		,"b1"},
						},



---==========================

	production = {

						{"repair-pack"							,"shinybob-tool1"				,"a1"},
						{"better-repair-pack"					,"shinybob-tool1"				,"a2"},
						{"iron-axe"							,"shinybob-tool1"				,"a3"},
						{"steel-axe"							,"shinybob-tool1"				,"a4"},
						{"brass-axe"							,"shinybob-tool1"				,"a5"},
						{"cobalt-axe"							,"shinybob-tool1"				,"a6"},
						{"titanium-axe"						,"shinybob-tool1"				,"a7"},
						{"tungsten-axe"						,"shinybob-tool1"				,"a8"},
						{"diamond-axe"							,"shinybob-tool1"				,"a9"},

						{"ping-tool"							,"shinybob-tool2"				,"a0"},
						{"module-inserter"						,"shinybob-tool2"				,"a1"},
						{"resource-monitor"						,"shinybob-tool2"				,"a2"},
						{"gun-nano-emitter"						,"shinybob-tool2"				,"a3"},
						{"ammo-nano-constructors"				,"shinybob-tool2"				,"a4"},
						{"ammo-nano-termites"					,"shinybob-tool2"				,"a5"},
						{"upgrade-builder"						,"shinybob-tool2"				,"a6"},
						{"upgrade-builder2"						,"shinybob-tool2"				,"a7"},
						{"magnet"								,"shinybob-tool2"				,"a8"},
						{"reverse-factory"						,"shinybob-tool2"				,"a9"},
						{"easy-copy-tool"						,"shinybob-tool2"				,"aa"},
						{"landmover-shovel"						,"shinybob-tool2"				,"ab"},

						{"steam-engine"						,"shinybob-steam"				,"a0"},
						{"steam-engine-2"						,"shinybob-steam"				,"a1"},
						{"steam-engine-3"						,"shinybob-steam"				,"a2"},
						{"boiler"								,"shinybob-steam"				,"a3"},
						{"boiler-2"							,"shinybob-steam"				,"a4"},
						{"boiler-3"							,"shinybob-steam"				,"a5"},
						{"boiler-4"							,"shinybob-steam"				,"a6"},
						{"burner-turbine"						,"shinybob-steam"				,"a7"},
						{"wind-turbine"   						,"shinybob-steam"   			,"a8"}, 		
						{"wind-turbine2"   						,"shinybob-steam"   			,"a9"}, 		
						{"wind-turbine3"   						,"shinybob-steam"   			,"aa"}, 		


						{"steam-turbine"						,"shinybob-nuke"				,"a0"},
						{"steam-turbine-2"						,"shinybob-nuke"				,"a1"},
						{"steam-turbine-3"						,"shinybob-nuke"				,"a2"},
						{"heat-exchanger"						,"shinybob-nuke"				,"a3"},
						{"heat-exchanger-2"						,"shinybob-nuke"				,"a4"},
						{"heat-exchanger-3"						,"shinybob-nuke"				,"a5"},
						{"fuel-processor"						,"shinybob-nuke"				,"a6"},
						{"centrifuge"							,"shinybob-nuke"				,"a7"},
						{"heat-pipe"							,"shinybob-nuke"				,"a8"},
						{"nuclear-reactor"						,"shinybob-nuke"				,"a9"},

						{"solar-panel-small"					,"shinybob-solar"				,"a1"},
						{"solar-panel-small-2"					,"shinybob-solar"				,"a4"},
						{"solar-panel-small-3"					,"shinybob-solar"				,"a7"},
						{"solar-panel"							,"shinybob-solar"				,"a2"},
						{"solar-panel-2"						,"shinybob-solar"				,"a5"},
						{"solar-panel-3"						,"shinybob-solar"				,"a8"},
						{"solar-panel-large"					,"shinybob-solar"				,"a3"},
						{"solar-panel-large-2"					,"shinybob-solar"				,"a6"},
						{"solar-panel-large-3"					,"shinybob-solar"				,"a9"},

						{"accumulator"							,"shinybob-accum"				,"a0"},
						{"fast-accumulator"						,"shinybob-accum"				,"a1"},
						{"fast-accumulator-2"					,"shinybob-accum"				,"a4"},
						{"fast-accumulator-3"					,"shinybob-accum"				,"a7"},
						{"large-accumulator"					,"shinybob-accum"				,"a2"},
						{"large-accumulator-2"					,"shinybob-accum"				,"a5"},
						{"large-accumulator-3"					,"shinybob-accum"				,"a8"},
						{"slow-accumulator"						,"shinybob-accum"				,"a3"},
						{"slow-accumulator-2"					,"shinybob-accum"				,"a6"},
						{"slow-accumulator-3"					,"shinybob-accum"				,"a9"},

						{"burner-mining-drill"					,"shinybob-miner"				,"a0"},
						{"electric-mining-drill"					,"shinybob-miner"				,"a1"},
						{"bob-mining-drill-1"					,"shinybob-miner"				,"a2"},
						{"bob-mining-drill-2"					,"shinybob-miner"				,"a3"},
						{"bob-mining-drill-3"					,"shinybob-miner"				,"a4"},
						{"bob-mining-drill-4"					,"shinybob-miner"				,"a5"},

						{"bob-area-mining-drill-1"				,"shinybob-miner"				,"b1"},
						{"bob-area-mining-drill-2"				,"shinybob-miner"				,"b2"},
						{"bob-area-mining-drill-3"				,"shinybob-miner"				,"b3"},
						{"bob-area-mining-drill-4"				,"shinybob-miner"				,"b4"},

						{"pumpjack"							,"shinybob-pump-jacks"			,"a1"},
						{"bob-pumpjack-1"						,"shinybob-pump-jacks"			,"a2"},
						{"bob-pumpjack-2"						,"shinybob-pump-jacks"			,"a3"},
						{"bob-pumpjack-3"						,"shinybob-pump-jacks"			,"a4"},
						{"bob-pumpjack-4"						,"shinybob-pump-jacks"			,"a5"},
						{"water-miner-1"						,"shinybob-pump-jacks"			,"b1"},
						{"water-miner-2"						,"shinybob-pump-jacks"			,"b2"},
						{"water-miner-3"						,"shinybob-pump-jacks"			,"b3"},
						{"water-miner-4"						,"shinybob-pump-jacks"			,"b4"},
						{"water-miner-5"						,"shinybob-pump-jacks"			,"b5"},

						{"stone-furnace"						,"shinybob-furnace1"			,"a1"},
						{"steel-furnace"						,"shinybob-furnace1"			,"a2"},
						{"electric-furnace"						,"shinybob-furnace1"			,"a3"},
						{"electric-furnace-2"					,"shinybob-furnace1"			,"a4"},
						{"electric-furnace-3"					,"shinybob-furnace1"			,"a5"},

						{"chemical-boiler"						,"shinybob-furnace2"			,"a1"},
						{"chemical-steel-furnace"				,"shinybob-furnace2"			,"a2"},
						{"chemical-furnace"						,"shinybob-furnace2"			,"a3"},
						{"electric-chemical-mixing-furnace"		,"shinybob-furnace2"			,"a4"},
						{"electric-chemical-mixing-furnace-2"		,"shinybob-furnace2"			,"a5"},

						{"mixing-furnace"						,"shinybob-furnace3"			,"a1"},
						{"mixing-steel-furnace"					,"shinybob-furnace3"			,"a2"},
						{"electric-mixing-furnace"				,"shinybob-furnace3"			,"a3"},

						{"burner-lab"							,"shinybob-lab"				,"a0"},
						{"lab"								,"shinybob-lab"				,"b1"},
						{"lab-module"							,"shinybob-lab"				,"b2"},
						{"lab-2"								,"shinybob-lab"				,"c1"},
						{"lab-alien"							,"shinybob-lab"				,"c2"},
						{"bob-greenhouse"						,"shinybob-lab"				,"d1"},

						{"burner-assembling-machine"				,"shinybob-assembling"			,"a0"},
						{"assembling-machine-1"					,"shinybob-assembling"			,"a1"},
						{"assembling-machine-2"					,"shinybob-assembling"			,"a2"},
						{"assembling-machine-3"					,"shinybob-assembling"			,"a3"},
						{"assembling-machine-4"					,"shinybob-assembling"			,"a4"},
						{"assembling-machine-5"					,"shinybob-assembling"			,"a5"},
						{"assembling-machine-6"					,"shinybob-assembling"			,"a6"},
						{"electronics-machine-1"					,"shinybob-assembling"			,"b1"},	
						{"electronics-machine-2"					,"shinybob-assembling"			,"b2"},	
						{"electronics-machine-3"					,"shinybob-assembling"			,"b3"},	

						{"electrolyser"						,"shinybob-electro"				,"a1"},
						{"electrolyser-2"						,"shinybob-electro"				,"a2"},
						{"electrolyser-3"						,"shinybob-electro"				,"a3"},
						{"electrolyser-4"						,"shinybob-electro"				,"a4"},

						{"chemical-plant"						,"shinybob-chem"				,"a1"},
						{"chemical-plant-2"						,"shinybob-chem"				,"a2"},
						{"chemical-plant-3"						,"shinybob-chem"				,"a3"},
						{"chemical-plant-4"						,"shinybob-chem"				,"a4"},

						{"oil-refinery"						,"shinybob-oilrefinery"			,"b1"},
						{"oil-refinery-2"						,"shinybob-oilrefinery"			,"b2"},
						{"oil-refinery-3"						,"shinybob-oilrefinery"			,"b3"},
						{"oil-refinery-4"						,"shinybob-oilrefinery"			,"b4"},
						},


---=====================


	modules = {
						{"module-case"							,"shinybob-modules0"			,"a1"},
						{"module-circuit-board"					,"shinybob-modules0"			,"a2"},
						{"module-contact"						,"shinybob-modules0"			,"a3"},

						{"module-processor-board" 				,"shinybob-modules1"			,"a1"},
						{"module-processor-board-2"				,"shinybob-modules1"			,"a2"},
						{"module-processor-board-3"				,"shinybob-modules1"			,"a3"},		    
						{"speed-processor"		 				,"shinybob-modules1"			,"a4"},		    
						{"speed-processor-2"					,"shinybob-modules1"			,"a5"},		    
						{"speed-processor-3"					,"shinybob-modules1"			,"a6"},		    
						{"effectivity-processor" 				,"shinybob-modules1"			,"a7"},		    
						{"effectivity-processor-2"				,"shinybob-modules1"			,"a8"},		    
						{"effectivity-processor-3"				,"shinybob-modules1"			,"a9"},		    

						{"productivity-processor"  				,"shinybob-modules2"			,"a1"},
						{"productivity-processor-2"				,"shinybob-modules2"			,"a2"},
						{"productivity-processor-3"				,"shinybob-modules2"			,"a3"},
						{"pollution-clean-processor"				,"shinybob-modules2"			,"a4"},
						{"pollution-clean-processor-2"			,"shinybob-modules2"			,"a5"},
						{"pollution-clean-processor-3"			,"shinybob-modules2"			,"a6"},
						{"pollution-create-processor" 			,"shinybob-modules2"			,"a7"},
						{"pollution-create-processor-2"			,"shinybob-modules2"			,"a8"},
						{"pollution-create-processor-3"			,"shinybob-modules2"			,"a9"},


--						{"speed-module" 						,""							,""},
--						{"speed-module-2"						,""							,""},
--						{"speed-module-3"						,""							,""},
--						{"speed-module-4"						,""							,""},
--						{"speed-module-5"						,""							,""},
--						{"speed-module-6"						,""							,""},
--						{"speed-module-7"						,""							,""},
--						{"speed-module-8"						,""							,""},
--
--						{"effectivity-module" 					,""							,""},
--						{"effectivity-module-2"					,""							,""},
--						{"effectivity-module-3"					,""							,""},
--						{"effectivity-module-4"					,""							,""},
--						{"effectivity-module-5"					,""							,""},
--						{"effectivity-module-6"					,""							,""},
--						{"effectivity-module-7"					,""							,""},
--						{"effectivity-module-8"					,""							,""},
--
--						{"productivity-module" 					,""							,""},
--						{"productivity-module-2"					,""							,""},
--						{"productivity-module-3"					,""							,""},
--						{"productivity-module-4"					,""							,""},
--						{"productivity-module-5"					,""							,""},
--						{"productivity-module-6"					,""							,""},
--						{"productivity-module-7"					,""							,""},
--						{"productivity-module-8"					,""							,""},
--
--						{"pollution-clean-module-1" 				,""							,""},
--						{"pollution-clean-module-2"				,""							,""},
--						{"pollution-clean-module-3"				,""							,""},
--						{"pollution-clean-module-4"				,""							,""},
--						{"pollution-clean-module-5"				,""							,""},
--						{"pollution-clean-module-6"				,""							,""},
--						{"pollution-clean-module-7"				,""							,""},
--						{"pollution-clean-module-8"				,""							,""},
--
--						{"pollution-create-module-1" 				,""							,""},
--						{"pollution-create-module-2"				,""							,""},
--						{"pollution-create-module-3"				,""							,""},
--						{"pollution-create-module-4"				,""							,""},
--						{"pollution-create-module-5"				,""							,""},
--						{"pollution-create-module-6"				,""							,""},
--						{"pollution-create-module-7"				,""							,""},
--						{"pollution-create-module-8"				,""							,""},
--
--						{"raw-speed-module-1" 					,""							,""},
--						{"raw-speed-module-2"					,""							,""},
--						{"raw-speed-module-3"					,""							,""},
--						{"raw-speed-module-4"					,""							,""},
--						{"raw-speed-module-5"					,""							,""},
--						{"raw-speed-module-6"					,""							,""},
--						{"raw-speed-module-7"					,""							,""},
--						{"raw-speed-module-8"					,""							,""},
--
--						{"green-module-1" 						,""							,""},
--						{"green-module-2"						,""							,""},
--						{"green-module-3"						,""							,""},
--						{"green-module-4"						,""							,""},
--						{"green-module-5"						,""							,""},
--						{"green-module-6"						,""							,""},
--						{"green-module-7"						,""							,""},
--						{"green-module-8"						,""							,""},
--
--						{"raw-productivity-module-1" 				,""							,""},
--						{"raw-productivity-module-2"				,""							,""},
--						{"raw-productivity-module-3"				,""							,""},
--						{"raw-productivity-module-4"				,""							,""},
--						{"raw-productivity-module-5"				,""							,""},
--						{"raw-productivity-module-6"				,""							,""},
--						{"raw-productivity-module-7"				,""							,""},
--						{"raw-productivity-module-8"				,""							,""},
--
--						{"god-module-1" 						,""							,""},
--						{"god-module-2"						,""							,""},
--						{"god-module-3"						,""							,""},
--						{"god-module-4"						,""							,""},
--						{"god-module-5"						,""							,""},
						
						
						
						},

--	beacons = {
--						{"beacon" 							,"",""},
--						{"beacon-2"							,"",""},
--						{"beacon-3"							,"",""},
--						},


---=====================


	intermediates = {
						{"empty-barrel"						,"shinybob-containers"			,"a1"},
						{"gas-canister"						,"shinybob-containers"			,"a2"},
						{"empty-canister"						,"shinybob-containers"			,"a3"},		    

						{"solid-fuel"							,"shinybob-engines"				,"a1"},
						{"enriched-fuel"						,"shinybob-engines"				,"a2"},
						{"iron-stick"							,"shinybob-engines"				,"a3"},
						{"engine-unit"							,"shinybob-engines"				,"a4"},
						{"electric-engine-unit"					,"shinybob-engines"				,"a5"},		    

						{"rocket-fuel"							,"shinybob-rocket-parts"			,"a1"},		    
						{"low-density-structure"					,"shinybob-rocket-parts"			,"a2"},		    
						{"rocket-control-unit"					,"shinybob-rocket-parts"			,"a3"},		    
						{"rocket-part"							,"shinybob-rocket-parts"			,"a4"},
						{"satellite"							,"shinybob-rocket-parts"			,"a5"},

						{"nuclear-fuel"						,"shinybob-nuclear"				,"a1"},		    
						{"uranium-fuel-cell"					,"shinybob-nuclear"				,"a2"},		    
						{"used-up-uranium-fuel-cell"				,"shinybob-nuclear"				,"a3"},		    
						{"nuclear-fuel-reprocessing"				,"shinybob-nuclear"				,"a4"},		    
						{"uranium-processing"					,"shinybob-nuclear"				,"a5"},		    
						{"kovarex-enrichment-process"				,"shinybob-nuclear"				,"a6"},		    
						{"uranium-235"							,"shinybob-nuclear"				,"a7"},
						{"uranium-238"							,"shinybob-nuclear"				,"a8"},

						{"science-pack-1"						,"shinybob-science-pack"			,"a0"},		    
						{"science-pack-2"						,"shinybob-science-pack"			,"a1"},		    
						{"science-pack-3"						,"shinybob-science-pack"			,"a2"},		    
						{"logistic-science-pack"					,"shinybob-science-pack"			,"a3"},		    
						{"production-science-pack"				,"shinybob-science-pack"			,"a4"},		    
						{"high-tech-science-pack"				,"shinybob-science-pack"			,"a5"},		    
						{"science-pack-gold"					,"shinybob-science-pack"			,"a6"},		    
						{"military-science-pack"					,"shinybob-science-pack"			,"a7"},		    
						{"space-science-pack"					,"shinybob-science-pack"			,"a8"},		    

						{"alien-science-pack-red"				,"shinybob-science-pack-alien"	,"a1"},		    
						{"alien-science-pack-green"				,"shinybob-science-pack-alien"	,"a2"},		    
						{"alien-science-pack-blue"				,"shinybob-science-pack-alien"	,"a3"},						
						{"alien-science-pack"					,"shinybob-science-pack-alien"	,"a4"},									
						{"alien-science-pack-purple"				,"shinybob-science-pack-alien"	,"a5"},
						{"alien-science-pack-yellow"				,"shinybob-science-pack-alien"	,"a6"},
						{"alien-science-pack-orange"				,"shinybob-science-pack-alien"	,"a7"},		    

						},

	seedlings = {
						{"bob-basic-greenhouse-cycle"   			,"shinybob-seedlings"			,"a1"},		    
						{"bob-advanced-greenhouse-cycle"   		,"shinybob-seedlings"			,"a2"},		    
						{"bob-seedling"	  					,"shinybob-seedlings"			,"a3"},		    
						{"bob-fertiliser"						,"shinybob-seedlings"			,"a4"},
						{"seedling"	  						,"shinybob-seedlings"			,"a5"},		    
						{"fertiliser"							,"shinybob-seedlings"			,"a6"},

						},

	alienartifacts = {
						{"small-alien-artifact"   	  			,"shinybob-small-allien-artifacts"	,"a1"},		    
						{"small-alien-artifact-red"	  			,"shinybob-small-allien-artifacts"	,"a2"},		    
						{"small-alien-artifact-orange"			,"shinybob-small-allien-artifacts"	,"a3"},						
						{"small-alien-artifact-yellow"			,"shinybob-small-allien-artifacts"	,"a4"},
						{"small-alien-artifact-green" 			,"shinybob-small-allien-artifacts"	,"a5"},		    
						{"small-alien-artifact-blue"  			,"shinybob-small-allien-artifacts"	,"a6"},
						{"small-alien-artifact-purple"			,"shinybob-small-allien-artifacts"	,"a7"},

						{"alien-artifact"   					,"shinybob-allien-artifacts"		,"a1"},		    
						{"alien-artifact-red"					,"shinybob-allien-artifacts"		,"a2"},		    
						{"alien-artifact-orange"					,"shinybob-allien-artifacts"		,"a3"},						
						{"alien-artifact-yellow"					,"shinybob-allien-artifacts"		,"a4"},
						{"alien-artifact-green" 					,"shinybob-allien-artifacts"		,"a5"},		    
						{"alien-artifact-blue"  					,"shinybob-allien-artifacts"		,"a6"},
						{"alien-artifact-purple"					,"shinybob-allien-artifacts"		,"a7"},

						},


---=====================
	fluids = {
						{"basic-oil-processing"					,"shinybob-petrol-fluids"		,"a0"},
						{"advanced-oil-processing"				,"shinybob-petrol-fluids"		,"a1"},
						{"bob-oil-processing"					,"shinybob-petrol-fluids"		,"a2"},

						{"coal-liquefaction"					,"shinybob-petrol-fluids"		,"a3"},
						{"coal-cracking"						,"shinybob-petrol-fluids"		,"a4"},
						{"heavy-oil-cracking"					,"shinybob-petrol-fluids"		,"a5"},
						{"light-oil-cracking"					,"shinybob-petrol-fluids"		,"a6"},
						{"petroleum-gas-cracking"				,"shinybob-petrol-fluids"		,"a7"},
						{"liquid-fuel"							,"shinybob-petrol-fluids"		,"a8"},
						{"lubricant"							,"shinybob-petrol-fluids"		,"a9"},

						{"oil-processing-with-sulfur"				,"shinybob-petrol-sulfur-fluids"	,"a1"},
						{"oil-processing-with-sulfur-dioxide"		,"shinybob-petrol-sulfur-fluids"	,"a2"},
						{"oil-processing-with-sulfur-dioxide-2"		,"shinybob-petrol-sulfur-fluids"	,"a3"},
						{"oil-processing-with-sulfur-dioxide-3"		,"shinybob-petrol-sulfur-fluids"	,"a4"},

						{"solid-fuel-from-heavy-oil"				,"shinybob-petrol-sulfur-fluids"	,"b1"},
						{"solid-fuel-from-light-oil"				,"shinybob-petrol-sulfur-fluids"	,"b2"},
						{"solid-fuel-from-petroleum-gas"			,"shinybob-petrol-sulfur-fluids"	,"b3"},
						{"solid-fuel-from-hydrogen"				,"shinybob-petrol-sulfur-fluids"	,"b4"},
						{"enriched-fuel-from-liquid-fuel"			,"shinybob-petrol-sulfur-fluids"	,"b5"},
						{"enriched-fuel-from-hydrazine"			,"shinybob-petrol-sulfur-fluids"	,"b6"},

						{"sulfur-dioxide"						,"shinybob-sulfur-fluids"		,"a1"},
						{"sulfuric-acid"						,"shinybob-sulfur-fluids"		,"a2"},
						{"sulfuric-acid-2"						,"shinybob-sulfur-fluids"		,"a3"},

						{"bob-liquid-air"						,"shinybob-nitrogen-fluids"		,"a1"},
						{"nitrogen" 							,"shinybob-nitrogen-fluids"		,"a2"},
						{"ammonia" 							,"shinybob-nitrogen-fluids"		,"a3"},
						{"nitric-oxide"						,"shinybob-nitrogen-fluids"		,"a4"},
						{"nitrogen-dioxide" 					,"shinybob-nitrogen-fluids"		,"a5"},
						{"nitric-acid" 						,"shinybob-nitrogen-fluids"		,"a6"},
						{"sulfuric-nitric-acid" 					,"shinybob-nitrogen-fluids"		,"a7"},
						{"nitroglycerin" 						,"shinybob-nitrogen-fluids"		,"a8"},
						{"glycerol" 							,"shinybob-nitrogen-fluids"		,"a9"},


						{"pure-water"							,"shinybob-pure-water-fluids"		,"a1"},
						{"pure-water-pump"						,"shinybob-pure-water-fluids"		,"a2"},
						{"pure-water-from-lithia" 				,"shinybob-pure-water-fluids"		,"a3"},


						{"lithium-water-electrolysis"				,"shinybob-hydrogen-fluids"		,"a1"},
						{"water-electrolysis" 					,"shinybob-hydrogen-fluids"		,"a2"},
						{"hydrogen-peroxide" 					,"shinybob-hydrogen-fluids"		,"a3"},
						{"hydrazine" 							,"shinybob-hydrogen-fluids"		,"a4"},
						{"dinitrogen-tetroxide"					,"shinybob-hydrogen-fluids"		,"a5"},

						{"salt-water-electrolysis"				,"shinybob-chloride-fluids"		,"a1"},
						{"hydrogen-chloride"					,"shinybob-chloride-fluids"		,"a2"},
						{"tungstic-acid"						,"shinybob-chloride-fluids"		,"a3"},
						{"ferric-chloride-solution"				,"shinybob-chloride-fluids"		,"a4"},
						},

	barreling = {
						{"fill-ammonia-barrel"					,"shinybob-loading-bottles"		,"a0"},
						{"fill-chlorine-barrel"					,"shinybob-loading-bottles"		,"a1"},
						{"fill-hydrogen-barrel"					,"shinybob-loading-bottles"		,"a2"},
						{"fill-hydrogen-chloride-barrel"			,"shinybob-loading-bottles"		,"a3"},
						{"fill-nitric-oxide-barrel"				,"shinybob-loading-bottles"		,"a4"},
						{"fill-nitrogen-barrel"					,"shinybob-loading-bottles"		,"a5"},
						{"fill-nitrogen-dioxide-barrel"			,"shinybob-loading-bottles"		,"a6"},
						{"fill-oxygen-barrel"					,"shinybob-loading-bottles"		,"a7"},
						{"fill-petroleum-gas-barrel"				,"shinybob-loading-bottles"		,"a8"},
						{"fill-sulfur-dioxide-barrel"				,"shinybob-loading-bottles"		,"a9"},

						{"empty-ammonia-barrel"					,"shinybob-empty-bottles"		,"a0"},
						{"empty-chlorine-barrel"					,"shinybob-empty-bottles"		,"a1"},
						{"empty-hydrogen-barrel"					,"shinybob-empty-bottles"		,"a2"},
						{"empty-hydrogen-chloride-barrel"			,"shinybob-empty-bottles"		,"a3"},
						{"empty-nitric-oxide-barrel"				,"shinybob-empty-bottles"		,"a4"},
						{"empty-nitrogen-barrel"					,"shinybob-empty-bottles"		,"a5"},
						{"empty-nitrogen-dioxide-barrel"			,"shinybob-empty-bottles"		,"a6"},
						{"empty-oxygen-barrel"					,"shinybob-empty-bottles"		,"a7"},
						{"empty-petroleum-gas-barrel"				,"shinybob-empty-bottles"		,"a8"},
						{"empty-sulfur-dioxide-barrel"			,"shinybob-empty-bottles"		,"a9"},

						{"fill-crude-oil-barrel"					,"shinybob-loading-barrels"		,"a1"},
						{"fill-heavy-oil-barrel"					,"shinybob-loading-barrels"		,"a2"},
						{"fill-light-oil-barrel"					,"shinybob-loading-barrels"		,"a3"},
						{"fill-lubricant-barrel"					,"shinybob-loading-barrels"		,"a4"},
						{"fill-water-barrel"					,"shinybob-loading-barrels"		,"a5"},
						{"fill-lithia-water-barrel"				,"shinybob-loading-barrels"		,"a6"},
						{"fill-ferric-chloride-solution-barrel"		,"shinybob-loading-barrels"		,"a7"},
						{"fill-liquid-fuel-barrel"				,"shinybob-loading-barrels"		,"a8"},

						{"empty-crude-oil-barrel"				,"shinybob-empty-barrels"		,"a1"},
						{"empty-heavy-oil-barrel"				,"shinybob-empty-barrels"		,"a2"},
						{"empty-light-oil-barrel"				,"shinybob-empty-barrels"		,"a3"},
						{"empty-lubricant-barrel"				,"shinybob-empty-barrels"		,"a4"},
						{"empty-water-barrel"					,"shinybob-empty-barrels"		,"a5"},
						{"empty-lithia-water-barrel"				,"shinybob-empty-barrels"		,"a6"},
						{"empty-ferric-chloride-solution-barrel"	,"shinybob-empty-barrels"		,"a7"},
						{"empty-liquid-fuel-barrel"				,"shinybob-empty-barrels"		,"a8"},

						{"fill-dinitrogen-tetroxide-barrel"		,"shinybob-loading-bob-barrels"	,"a0"},
						{"fill-glycerol-barrel"					,"shinybob-loading-bob-barrels"	,"a1"},
						{"fill-hydrazine-barrel"					,"shinybob-loading-bob-barrels"	,"a2"},
						{"fill-hydrogen-peroxide-barrel"			,"shinybob-loading-bob-barrels"	,"a3"},
						{"fill-nitric-acid-barrel"				,"shinybob-loading-bob-barrels"	,"a4"},
						{"fill-nitroglycerin-barrel"				,"shinybob-loading-bob-barrels"	,"a5"},
						{"fill-pure-water-barrel"				,"shinybob-loading-bob-barrels"	,"a6"},
						{"fill-sulfuric-acid-barrel"				,"shinybob-loading-bob-barrels"	,"a7"},
						{"fill-sulfuric-nitric-acid-barrel"		,"shinybob-loading-bob-barrels"	,"a8"},
						{"fill-tungstic-acid-barrel"				,"shinybob-loading-bob-barrels"	,"a9"},

						{"empty-dinitrogen-tetroxide-barrel"		,"shinybob-empty-bob-barrels"		,"a0"},
						{"empty-glycerol-barrel"					,"shinybob-empty-bob-barrels"		,"a1"},
						{"empty-hydrazine-barrel"				,"shinybob-empty-bob-barrels"		,"a2"},
						{"empty-hydrogen-peroxide-barrel"			,"shinybob-empty-bob-barrels"		,"a3"},
						{"empty-nitric-acid-barrel"				,"shinybob-empty-bob-barrels"		,"a4"},
						{"empty-nitroglycerin-barrel"				,"shinybob-empty-bob-barrels"		,"a5"},
						{"empty-pure-water-barrel"				,"shinybob-empty-bob-barrels"		,"a6"},
						{"empty-sulfuric-acid-barrel"				,"shinybob-empty-bob-barrels"		,"a7"},
						{"empty-sulfuric-nitric-acid-barrel"		,"shinybob-empty-bob-barrels"		,"a8"},
						{"empty-tungstic-acid-barrel"				,"shinybob-empty-bob-barrels"		,"a9"},

						{"fill-alien-acid-barrel"				,"shinybob-loading-alien-barrels"	,"a1"},
						{"fill-alien-explosive-barrel"			,"shinybob-loading-alien-barrels"	,"a2"},
						{"fill-alien-fire-barrel"				,"shinybob-loading-alien-barrels"	,"a3"},
						{"fill-alien-poison-barrel"				,"shinybob-loading-alien-barrels"	,"a4"},

						{"empty-alien-acid-barrel"				,"shinybob-empty-alien-barrels"	,"a1"},
						{"empty-alien-explosive-barrel"			,"shinybob-empty-alien-barrels"	,"a2"},
						{"empty-alien-fire-barrel"				,"shinybob-empty-alien-barrels"	,"a3"},
						{"empty-alien-poison-barrel"				,"shinybob-empty-alien-barrels"	,"a4"},

						},


	barrels = {
						{"ammonia-barrel"						,"shinybob-bottles"				,"a0"},
						{"chlorine-barrel"						,"shinybob-bottles"				,"a1"},
						{"hydrogen-barrel"						,"shinybob-bottles"				,"a2"},
						{"hydrogen-chloride-barrel"				,"shinybob-bottles"				,"a3"},
						{"nitric-oxide-barrel"					,"shinybob-bottles"				,"a4"},
						{"nitrogen-barrel"						,"shinybob-bottles"				,"a5"},
						{"nitrogen-dioxide-barrel"				,"shinybob-bottles"				,"a6"},
						{"oxygen-barrel"						,"shinybob-bottles"				,"a7"},
						{"petroleum-gas-barrel"					,"shinybob-bottles"				,"a8"},
						{"sulfur-dioxide-barrel"					,"shinybob-bottles"				,"a9"},

						{"crude-oil-barrel"						,"shinybob-barrels"				,"a1"},
						{"heavy-oil-barrel"						,"shinybob-barrels"				,"a2"},
						{"light-oil-barrel"						,"shinybob-barrels"				,"a3"},
						{"lubricant-barrel"						,"shinybob-barrels"				,"a4"},
						{"water-barrel"						,"shinybob-barrels"				,"a5"},
						{"lithia-water-barrel"					,"shinybob-barrels"				,"a6"},
						{"ferric-chloride-solution-barrel"			,"shinybob-barrels"				,"a7"},
						{"liquid-fuel-barrel"					,"shinybob-barrels"				,"a8"},

						{"dinitrogen-tetroxide-barrel"			,"shinybob-bob-barrels"			,"a1"},
						{"glycerol-barrel"						,"shinybob-bob-barrels"			,"a2"},
						{"hydrazine-barrel"						,"shinybob-bob-barrels"			,"a3"},
						{"hydrogen-peroxide-barrel"				,"shinybob-bob-barrels"			,"a4"},
						{"nitric-acid-barrel"					,"shinybob-bob-barrels"			,"a5"},
						{"nitroglycerin-barrel"					,"shinybob-bob-barrels"			,"a6"},
						{"sulfuric-acid-barrel"					,"shinybob-bob-barrels"			,"a7"},
						{"sulfuric-nitric-acid-barrel"			,"shinybob-bob-barrels"			,"a8"},
						{"tungstic-acid-barrel"					,"shinybob-bob-barrels"			,"a9"},

						{"alien-acid-barrel"					,"shinybob-alien-barrels"		,"a1"},
						{"alien-explosive-barrel"				,"shinybob-alien-barrels"		,"a2"},
						{"alien-fire-barrel"					,"shinybob-alien-barrels"		,"a3"},
						{"alien-poison-barrel"					,"shinybob-alien-barrels"		,"a4"},

						},


---=====================
	materials = {
						{"raw-wood"							,"shinybob-ores"				,"a1"},
						{"coal"								,"shinybob-ores"				,"a2"},
						{"stone"								,"shinybob-ores"				,"a3"},
						{"iron-ore"							,"shinybob-ores"				,"a4"},
						{"copper-ore"							,"shinybob-ores"				,"a5"},
						{"uranium-ore"							,"shinybob-ores"				,"a6"},

						{"bauxite-ore"							,"shinybob-ores"				,"b1"},
						{"cobalt-ore"							,"shinybob-ores"				,"b2"},
						{"gold-ore"							,"shinybob-ores"				,"b3"},
						{"lead-ore"							,"shinybob-ores"				,"b4"},
						{"nickel-ore"							,"shinybob-ores"				,"b5"},
						{"quartz"								,"shinybob-ores"				,"b6"},
						{"rutile-ore"							,"shinybob-ores"				,"c1"},
						{"silver-ore"							,"shinybob-ores"				,"c2"},
						{"thorium-ore"							,"shinybob-ores"				,"c3"},
						{"tin-ore"							,"shinybob-ores"				,"c4"},
						{"tungsten-ore"						,"shinybob-ores"				,"c5"},
						{"zinc-ore"							,"shinybob-ores"				,"c6"},
						{"sulfur"								,"shinybob-ores"				,"d1"},
						{"raw-fish"							,"shinybob-ores"				,"d2"},

						{"wood"								,"shinybob-resource1"			,"a1"},
						{"bob-resin-wood"						,"shinybob-resource1"			,"a2"},
						{"resin"								,"shinybob-resource1"			,"a2"},
						{"gun-cotton"							,"shinybob-resource1"			,"a3"},
						{"gun-cotton-synthetic"					,"shinybob-resource1"			,"a4"},
						{"silicon-powder"						,"shinybob-resource1"			,"a5"},
						{"silicon-wafer"						,"shinybob-resource1"			,"a6"},
						{"heat-shield-tile"						,"shinybob-resource1"			,"a7"},

						{"synthetic-wood"						,"shinybob-resource2"			,"a0"},
						{"bob-resin-oil"						,"shinybob-resource2"			,"a1"},
						{"calcium-chloride"						,"shinybob-resource2"			,"a2"},
						{"lead-oxide"							,"shinybob-resource2"			,"a3"},
						{"silver-nitrate"						,"shinybob-resource2"			,"a4"},
						{"silver-oxide"						,"shinybob-resource2"			,"a5"},
						{"petroleum-jelly"						,"shinybob-resource2"			,"a6"},
						{"sulfur-2"							,"shinybob-resource2"			,"a9"},
						{"plastic-bar"							,"shinybob-resource2"			,"aa"},

						{"copper-plate"						,"shinybob-plates0"				,"a1"},
						{"iron-plate"							,"shinybob-plates0"				,"a2"},
						{"steel-plate"							,"shinybob-plates0"				,"a3"},
						{"stone-brick"							,"shinybob-plates0"				,"a4"},
						{"concrete"							,"shinybob-plates0"				,"a5"},
						{"hazard-concrete"						,"shinybob-plates0"				,"a6"},
						{"landfill"							,"shinybob-plates0"				,"a7"},
						{"waterfill"							,"shinybob-plates0"				,"a8"},
						{"landmover"							,"shinybob-plates0"				,"a9"},

						{"tin-plate"							,"shinybob-plates1"				,"a1"},
						{"lead-plate"							,"shinybob-plates1"				,"a2"},
						{"silver-plate"						,"shinybob-plates1"				,"a3"},
						{"quartz-glass"						,"shinybob-plates1"				,"a4"},						
						{"glass"								,"shinybob-plates1"				,"a4"},						
						{"bob-rubber"							,"shinybob-plates1"				,"a5"},
						{"rubber"								,"shinybob-plates1"				,"a5"},

						{"cobalt-oxide-from-copper"				,"shinybob-plates2"				,"a0"},
						{"bob-lead-plate"						,"shinybob-plates2"				,"a1"},
						{"silver-from-lead"						,"shinybob-plates2"				,"a2"},
						{"bob-gold-plate"						,"shinybob-plates2"				,"a3"},
						{"gold-plate"							,"shinybob-plates2"				,"a3"},
						{"cobalt-oxide"						,"shinybob-plates2"				,"a4"},
						{"cobalt-plate"						,"shinybob-plates2"				,"a5"},
						{"lithium-cobalt-oxide"					,"shinybob-plates2"				,"a6"},
						{"lithium-chloride"						,"shinybob-plates2"				,"a7"},
						{"salt"								,"shinybob-plates2"				,"a8"},
						{"alumina"							,"shinybob-plates2"				,"a9"},
						{"carbon"								,"shinybob-plates2"				,"aa"},
						{"silicon-nitride"						,"shinybob-plates2"				,"ab"},
						{"silicon-carbide"						,"shinybob-plates2"				,"ac"},
						{"powdered-tungsten"					,"shinybob-plates2"				,"ad"},
						{"tungsten-oxide"						,"shinybob-plates2"				,"ae"},

						{"bob-aluminium-plate"					,"shinybob-material1"			,"a1"},
						{"aluminium-plate"						,"shinybob-material1"			,"a1"},
						{"bob-zinc-plate"						,"shinybob-material1"			,"a2"},
						{"zinc-plate"							,"shinybob-material1"			,"a2"},
						{"bob-titanium-plate"					,"shinybob-material1"			,"a3"},
						{"titanium-plate"						,"shinybob-material1"			,"a3"},
						{"lithium"							,"shinybob-material1"			,"a4"},
						{"lithium-perchlorate"					,"shinybob-material1"			,"a4"},
						{"bob-silicon-plate"					,"shinybob-material1"			,"a5"},
						{"silicon"							,"shinybob-material1"			,"a5"},
						{"bob-nickel-plate"						,"shinybob-material1"			,"a6"},
						{"nickel-plate"						,"shinybob-material1"			,"a6"},
						{"sodium-hydroxide"						,"shinybob-material1"			,"a7"},

						{"bronze-alloy"						,"shinybob-material2"			,"a0"},
						{"brass-alloy"							,"shinybob-material2"			,"a1"},
						{"bob-tungsten-plate"					,"shinybob-material2"			,"a2"},
						{"tungsten-plate"						,"shinybob-material2"			,"a2"},
						{"copper-tungsten-alloy"					,"shinybob-material2"			,"a3"},
						{"tungsten-carbide"						,"shinybob-material2"			,"a4"},
						{"tungsten-carbide-2"					,"shinybob-material2"			,"a5"},
						{"gunmetal-alloy"						,"shinybob-material2"			,"a6"},
						{"electrum-alloy"						,"shinybob-material2"			,"a7"},
						{"invar-alloy"							,"shinybob-material2"			,"a8"},
						{"nitinol-alloy"						,"shinybob-material2"			,"a9"},
						{"solder-alloy"						,"shinybob-material2"			,"aa"},
						{"solder-alloy-lead"					,"shinybob-material2"			,"ab"},
						{"cobalt-steel-alloy"					,"shinybob-material2"			,"ac"},

						},

---=====================
	bobsmaterials = {

						{"bullet-casing"						,"shinybob-base-ammo"			,"a0"},
						{"cordite"							,"shinybob-base-ammo"			,"a1"},
						{"laser-rifle-battery-case"				,"shinybob-base-ammo"			,"a2"},
						{"magazine"							,"shinybob-base-ammo"			,"a3"},
						{"shot"								,"shinybob-base-ammo"			,"a4"},
						{"shotgun-shell-casing"					,"shinybob-base-ammo"			,"a5"},
						{"rocket-engine"						,"shinybob-base-ammo"			,"a6"},
						{"rocket-body"							,"shinybob-base-ammo"			,"a7"},

						{"bullet-projectile"					,"shinybob-projectile"			,"a1"},
						{"he-bullet-projectile"					,"shinybob-projectile"			,"a2"},
						{"electric-bullet-projectile"				,"shinybob-projectile"			,"a3"},
						{"flame-bullet-projectile"				,"shinybob-projectile"			,"a4"},
						{"ap-bullet-projectile"					,"shinybob-projectile"			,"a5"},
						{"acid-bullet-projectile"				,"shinybob-projectile"			,"a6"},
						{"poison-bullet-projectile"				,"shinybob-projectile"			,"a7"},
						{"uranium-bullet-projectile"				,"shinybob-projectile"			,"a8"},

						{"bullet"								,"shinybob-bullets"				,"a1"},
						{"he-bullet"							,"shinybob-bullets"				,"a2"},
						{"electric-bullet"						,"shinybob-bullets"				,"a3"},
						{"flame-bullet"						,"shinybob-bullets"				,"a4"},
						{"ap-bullet"							,"shinybob-bullets"				,"a5"},
						{"acid-bullet"							,"shinybob-bullets"				,"a6"},
						{"poison-bullet"						,"shinybob-bullets"				,"a7"},
						{"uranium-bullet"						,"shinybob-bullets"				,"a8"},

						{"rocket-warhead"						,"shinybob-warhead"				,"a1"},
						{"explosive-rocket-warhead"				,"shinybob-warhead"				,"a2"},
						{"electric-rocket-warhead" 				,"shinybob-warhead"				,"a3"},
						{"flame-rocket-warhead"					,"shinybob-warhead"				,"a4"},
						{"piercing-rocket-warhead"				,"shinybob-warhead"				,"a5"},
						{"acid-rocket-warhead"					,"shinybob-warhead"				,"a6"},
						{"poison-rocket-warhead"					,"shinybob-warhead"				,"a7"},
						{"uranium-rocket-warhead"				,"shinybob-warhead"				,"a8"},

						{"battery"							,"shinybob-batteries"			,"a1"},
						{"lithium-ion-battery"					,"shinybob-batteries"			,"a2"},
						{"silver-zinc-battery"					,"shinybob-batteries"			,"a3"},
						{"grinding-wheel"						,"shinybob-batteries"			,"a4"},
						{"polishing-wheel"						,"shinybob-batteries"			,"a5"},
						{"polishing-compound"					,"shinybob-batteries"			,"a6"},

						{"copper-cable"						,"shinybob-wires"				,"a1"},
						{"tinned-copper-cable"					,"shinybob-wires"				,"a2"},
						{"insulated-cable"						,"shinybob-wires"				,"a3"},
						{"gilded-copper-cable"					,"shinybob-wires"				,"a4"},
						{"red-wire"							,"shinybob-wires"				,"a5"},
						{"green-wire"							,"shinybob-wires"				,"a6"},

						{"solder"								,"shinybob-electronics"			,"a1"},
						{"basic-electronic-components"			,"shinybob-electronics"			,"a2"},
						{"electronic-components"					,"shinybob-electronics"			,"a3"},
						{"intergrated-electronics"				,"shinybob-electronics"			,"a4"},
						{"processing-electronics"				,"shinybob-electronics"			,"a5"},

						{"wooden-board"						,"shinybob-boards"				,"a1"},
						{"phenolic-board"						,"shinybob-boards"				,"a2"},
						{"fibreglass-board"						,"shinybob-boards"				,"a3"},

						{"basic-circuit-board"					,"shinybob-circuits"			,"a1"},
						{"circuit-board"						,"shinybob-circuits"			,"a2"},
						{"superior-circuit-board"				,"shinybob-circuits"			,"a3"},
						{"multi-layer-circuit-board"				,"shinybob-circuits"			,"a4"},

						{"electronic-circuit"					,"shinybob-elect-circuits"		,"a1"},
						{"advanced-circuit"						,"shinybob-elect-circuits"		,"a2"},
						{"processing-unit"						,"shinybob-elect-circuits"		,"a3"},
						{"advanced-processing-unit"				,"shinybob-elect-circuits"		,"a4"},

						{"steel-gear-wheel"						,"shinybob-gear-wheels"			,"a1"},
						{"brass-gear-wheel"						,"shinybob-gear-wheels"			,"a2"},
						{"titanium-gear-wheel"					,"shinybob-gear-wheels"			,"a3"},
						{"nitinol-gear-wheel"					,"shinybob-gear-wheels"			,"a4"},
						{"tungsten-gear-wheel"					,"shinybob-gear-wheels"			,"a5"},
						{"iron-gear-wheel"						,"shinybob-gear-wheels"			,"a6"},

						{"steel-bearing-ball"					,"shinybob-bearing-balls"		,"a1"},
						{"ceramic-bearing-ball"					,"shinybob-bearing-balls"		,"a2"},
						{"titanium-bearing-ball"					,"shinybob-bearing-balls"		,"a3"},
						{"nitinol-bearing-ball"					,"shinybob-bearing-balls"		,"a4"},

						{"steel-bearing"						,"shinybob-bearings"			,"a1"},
						{"ceramic-bearing"						,"shinybob-bearings"			,"a2"},
						{"titanium-bearing"						,"shinybob-bearings"			,"a3"},
						{"nitinol-bearing"						,"shinybob-bearings"			,"a4"},

						},

--[=====================
	combat = {
						{"pistol"								,"shinybob-guns"         		,"a0"},
						{"submachine-gun"						,"shinybob-guns"         		,"a1"},
						{"rifle"								,"shinybob-guns"         		,"a2"},
						{"sniper-rifle"						,"shinybob-guns"         		,"a3"},
						{"laser-rifle"							,"shinybob-guns"         		,"a4"},
						{"shotgun"							,"shinybob-guns"         		,"a5"},
						{"combat-shotgun"						,"shinybob-guns"         		,"a6"},
						{"rocket-launcher"						,"shinybob-guns"         		,"a7"},
						{"flamethrower"						,"shinybob-guns"         		,"a8"},
						{"flamethrower-ammo"					,"shinybob-guns"         		,"a9"},

						{"firearm-magazine"						,"shinybob-base-magazine"		,"a0"},
						{"piercing-rounds-magazine"				,"shinybob-base-magazine"		,"a1"},
						{"uranium-rounds-magazine"				,"shinybob-base-magazine"		,"a2"},
						{"shotgun-shell"						,"shinybob-base-magazine"		,"a3"},
						{"piercing-shotgun-shell"				,"shinybob-base-magazine"		,"a4"},
						{"grenade"							,"shinybob-base-magazine"		,"a5"},
						{"cluster-grenade"						,"shinybob-base-magazine"		,"a6"},
						{"explosives"							,"shinybob-base-magazine"		,"a8"},
						{"cliff-explosives"						,"shinybob-base-magazine"		,"a9"},

						{"cannon-shell"						,"shinybob-canon-shell"			,"a0"},
						{"explosive-cannon-shell"				,"shinybob-canon-shell"			,"a1"},
						{"scatter-cannon-shell"					,"shinybob-canon-shell"			,"a2"},
						{"uranium-cannon-shell"					,"shinybob-canon-shell"			,"a3"},
						{"explosive-uranium-cannon-shell"			,"shinybob-canon-shell"			,"a4"},
						{"rocket"								,"shinybob-canon-shell"			,"a5"},
						{"explosive-rocket"						,"shinybob-canon-shell"			,"a6"},
						{"atomic-bomb"							,"shinybob-canon-shell"			,"a7"},

						{"artillery-shell"						,"shinybob-artillery-shell"		,"a1"},
						{"explosive-artillery-shell"				,"shinybob-artillery-shell"		,"a2"},
						{"poison-artillery-shell"				,"shinybob-artillery-shell"		,"a3"},
						{"distractor-artillery-shell"				,"shinybob-artillery-shell"		,"a4"},
						{"artillery-targeting-remote"				,"shinybob-artillery-shell"		,"a5"},

						{"bullet-magazine"						,"shinybob-magazine"			,"a1"},
						{"he-bullet-magazine"					,"shinybob-magazine"			,"a2"},
						{"electric-bullet-magazine"				,"shinybob-magazine"			,"a3"},
						{"flame-bullet-magazine"					,"shinybob-magazine"			,"a4"},
						{"ap-bullet-magazine"					,"shinybob-magazine"			,"a5"},
						{"acid-bullet-magazine"					,"shinybob-magazine"			,"a6"},
						{"poison-bullet-magazine"				,"shinybob-magazine"			,"a7"},
						{"impact-bullet-magazine"				,"shinybob-magazine"			,"a8"},

						{"better-shotgun-shell"					,"shinybob-shotgun"				,"a1"},
						{"shotgun-explosive-shell"				,"shinybob-shotgun"				,"a2"},
						{"shotgun-electric-shell"				,"shinybob-shotgun"				,"a3"},
						{"shotgun-flame-shell"					,"shinybob-shotgun"				,"a4"},
						{"shotgun-ap-shell"						,"shinybob-shotgun"				,"a5"},
						{"shotgun-acid-shell"					,"shinybob-shotgun"				,"a6"},
						{"shotgun-poison-shell"					,"shinybob-shotgun"				,"a7"},
						{"shotgun-impact-shell"					,"shinybob-shotgun"				,"a8"},

						{"bob-rocket"							,"shinybob-rocket"				,"a1"},
						{"bob-explosive-rocket"					,"shinybob-rocket"				,"a2"},
						{"bob-electric-rocket"					,"shinybob-rocket"				,"a3"},
						{"bob-flame-rocket"						,"shinybob-rocket"				,"a4"},
						{"bob-piercing-rocket"					,"shinybob-rocket"				,"a5"},
						{"bob-acid-rocket"						,"shinybob-rocket"				,"a6"},
						{"bob-poison-rocket"					,"shinybob-rocket"				,"a7"},
						{"bob-impact-rocket"					,"shinybob-rocket"				,"a8"},

						{"laser-rifle-battery"					,"shinybob-laser-rifle"			,"a1"},
						{"laser-rifle-battery-ruby"				,"shinybob-laser-rifle"			,"a2"},
						{"laser-rifle-battery-sapphire"			,"shinybob-laser-rifle"			,"a3"},
						{"laser-rifle-battery-emerald"			,"shinybob-laser-rifle"			,"a4"},
						{"laser-rifle-battery-amethyst"			,"shinybob-laser-rifle"			,"a5"},
						{"laser-rifle-battery-topaz"				,"shinybob-laser-rifle"			,"a6"},
						{"laser-rifle-battery-diamond"			,"shinybob-laser-rifle"			,"a7"},
						{"laser-beam-rifle-ammo"					,"shinybob-laser-rifle"			,"a8"},

						{"robot-brain-combat"					,"shinybob-robots-combat-parts3"	,"a1"},
						{"robot-brain-combat-2"					,"shinybob-robots-combat-parts3"	,"a2"},
						{"robot-brain-combat-3"					,"shinybob-robots-combat-parts3"	,"a3"},
						{"robot-brain-combat-4"					,"shinybob-robots-combat-parts3"	,"a4"},												 
						{"robot-tool-combat"					,"shinybob-robots-combat-parts3"	,"b1"},
						{"robot-tool-combat-2"					,"shinybob-robots-combat-parts3"	,"b2"},
						{"robot-tool-combat-3"					,"shinybob-robots-combat-parts3"	,"b3"},
						{"robot-tool-combat-4"					,"shinybob-robots-combat-parts3"	,"b4"},

						{"defender-robot"						,"shinybob-robots1"				,"a1"},
						{"distractor-robot"						,"shinybob-robots1"				,"a2"},
						{"destroyer-robot"						,"shinybob-robots1"				,"a3"},
						{"bob-laser-robot"						,"shinybob-robots1"				,"a4"},
						{"poison-capsule"						,"shinybob-robots1"				,"a5"},
						{"slowdown-capsule"						,"shinybob-robots1"				,"a6"},

						{"defender-capsule"						,"shinybob-mines1"				,"a0"},
						{"distractor-capsule"					,"shinybob-mines1"				,"a1"},
						{"destroyer-capsule"					,"shinybob-mines1"				,"a2"},
						{"bob-laser-robot-capsule"				,"shinybob-mines1"				,"a3"},
						{"poison-mine"							,"shinybob-mines1"				,"a4"},
						{"slowdown-mine"						,"shinybob-mines1"				,"a5"},
						{"land-mine"							,"shinybob-mines1"				,"a6"},
						{"distractor-mine"						,"shinybob-mines1"				,"a7"},
						{"bob-robot-tank"						,"shinybob-mines1"				,"a8"},

						{"exoskeleton-equipment"  				,"shinybob-equipment1"			,"a0"},
						{"exoskeleton-equipment-2"				,"shinybob-equipment1"			,"a1"},
						{"exoskeleton-equipment-3"				,"shinybob-equipment1"			,"a2"},
						{"night-vision-equipment"  				,"shinybob-equipment1"			,"a3"},
						{"night-vision-equipment-2"				,"shinybob-equipment1"			,"a4"},
						{"night-vision-equipment-3"				,"shinybob-equipment1"			,"a5"},
						{"personal-roboport-equipment"    			,"shinybob-equipment1"			,"a6"},
						{"personal-roboport-mk2-equipment"			,"shinybob-equipment1"			,"a7"},
						{"belt-immunity-equipment"				,"shinybob-equipment1"			,"a8"},
						{"combat-robot-dispenser-equipment"		,"shinybob-equipment1"			,"a9"},

						{"battery-equipment"    					,"shinybob-equipment2"			,"a0"},
						{"battery-mk2-equipment"					,"shinybob-equipment2"			,"a1"},
						{"battery-mk3-equipment"					,"shinybob-equipment2"			,"a2"},
						{"battery-mk4-equipment"					,"shinybob-equipment2"			,"a3"},
						{"battery-mk5-equipment"					,"shinybob-equipment2"			,"a4"},
						{"battery-mk6-equipment"					,"shinybob-equipment2"			,"a5"},
						{"solar-panel-equipment"  				,"shinybob-equipment2"			,"a6"},
						{"solar-panel-equipment-2"				,"shinybob-equipment2"			,"a7"},
						{"solar-panel-equipment-3"				,"shinybob-equipment2"			,"a8"},
						{"solar-panel-equipment-4"				,"shinybob-equipment2"			,"a9"},

						{"energy-shield-equipment"				,"shinybob-equipment3"			,"a0"},
						{"energy-shield-mk2-equipment"			,"shinybob-equipment3"			,"a1"},
						{"energy-shield-mk3-equipment"			,"shinybob-equipment3"			,"a2"},
						{"energy-shield-mk4-equipment"			,"shinybob-equipment3"			,"a3"},
						{"energy-shield-mk5-equipment"			,"shinybob-equipment3"			,"a4"},
						{"energy-shield-mk6-equipment"			,"shinybob-equipment3"			,"a5"},
						{"fusion-reactor-equipment"				,"shinybob-equipment3"			,"a6"},
						{"fusion-reactor-equipment-2"				,"shinybob-equipment3"			,"a7"},
						{"fusion-reactor-equipment-3"				,"shinybob-equipment3"			,"a8"},
						{"fusion-reactor-equipment-4"				,"shinybob-equipment3"			,"a9"},

						{"personal-laser-defense-equipment"  		,"shinybob-equipment4"			,"a0"},
						{"personal-laser-defense-equipment-2"		,"shinybob-equipment4"			,"a1"},
						{"personal-laser-defense-equipment-3"		,"shinybob-equipment4"			,"a2"},
						{"personal-laser-defense-equipment-4"		,"shinybob-equipment4"			,"a3"},
						{"personal-laser-defense-equipment-5"		,"shinybob-equipment4"			,"a4"},
						{"personal-laser-defense-equipment-6"		,"shinybob-equipment4"			,"a5"},
						{"discharge-defense-equipment"			,"shinybob-equipment4"			,"a6"},
						{"discharge-defense-remote"				,"shinybob-equipment4"			,"a7"},

						{"gun-turret"							,"shinybob-turrets1"			,"a0"},
						{"bob-gun-turret-2"						,"shinybob-turrets1"			,"a1"},
						{"bob-gun-turret-3"						,"shinybob-turrets1"			,"a2"},
						{"bob-gun-turret-4"						,"shinybob-turrets1"			,"a3"},
						{"bob-gun-turret-5"						,"shinybob-turrets1"			,"a4"},
						{"bob-sniper-turret-1"					,"shinybob-turrets1"			,"a5"},
						{"bob-sniper-turret-2"					,"shinybob-turrets1"			,"a6"},
						{"bob-sniper-turret-3"					,"shinybob-turrets1"			,"a7"},
						{"orbital-ion-cannon"					,"shinybob-turrets1"			,"a8"},
						{"ion-cannon-targeter"					,"shinybob-turrets1"			,"a9"},

						{"laser-turret"						,"shinybob-turrets2"			,"a0"},
						{"bob-laser-turret-2"					,"shinybob-turrets2"			,"a1"},
						{"bob-laser-turret-3"					,"shinybob-turrets2"			,"a2"},
						{"bob-laser-turret-4"					,"shinybob-turrets2"			,"a3"},
						{"bob-laser-turret-5"					,"shinybob-turrets2"			,"a4"},
						{"artillery-turret"						,"shinybob-turrets2"			,"a5"},
						{"bob-artillery-turret-2"				,"shinybob-turrets2"			,"a6"},
						{"bob-artillery-turret-3"				,"shinybob-turrets2"			,"a7"},
						{"flamethrower-turret"					,"shinybob-turrets2"			,"a8"},
						{"rocket-silo"							,"shinybob-turrets2"			,"a9"},

						{"radar"  							,"shinybob-walls"				,"a0"},
						{"radar-2"							,"shinybob-walls"				,"a1"},
						{"radar-3"							,"shinybob-walls"				,"a2"},
						{"radar-4"							,"shinybob-walls"				,"a3"},
						{"radar-5"							,"shinybob-walls"				,"a4"},
						{"radar-mk2"							,"shinybob-walls"				,"a5"},
						{"radar-mk3"							,"shinybob-walls"				,"a6"},
						{"radar-mk4"							,"shinybob-walls"				,"a7"},
						{"radar-mk5"							,"shinybob-walls"				,"a8"},
						{"stone-wall"							,"shinybob-walls"				,"a9"},
						{"gate"								,"shinybob-walls"				,"aa"},
						{"reinforced-wall"						,"shinybob-walls"				,"ab"},
						{"reinforced-gate"						,"shinybob-walls"				,"ac"},

						},



---=====================
	equipment = {
						{"vehicle-solar-panel-1"					,"shinybob-bob-vehicleequipment-1"	,"a1"},
						{"vehicle-solar-panel-2"					,"shinybob-bob-vehicleequipment-1"	,"a2"},
						{"vehicle-solar-panel-3"					,"shinybob-bob-vehicleequipment-1"	,"a3"},
						{"vehicle-solar-panel-4"					,"shinybob-bob-vehicleequipment-1"	,"a4"},
						{"vehicle-solar-panel-5"					,"shinybob-bob-vehicleequipment-1"	,"a5"},
						{"vehicle-solar-panel-6"					,"shinybob-bob-vehicleequipment-1"	,"a6"},

						{"vehicle-fusion-reactor-1"				,"shinybob-bob-vehicleequipment-2"	,"a1"},
						{"vehicle-fusion-reactor-2"				,"shinybob-bob-vehicleequipment-2"	,"a2"},
						{"vehicle-fusion-reactor-3"				,"shinybob-bob-vehicleequipment-2"	,"a3"},
						{"vehicle-fusion-reactor-4"				,"shinybob-bob-vehicleequipment-2"	,"a4"},
						{"vehicle-fusion-reactor-5"				,"shinybob-bob-vehicleequipment-2"	,"a5"},
						{"vehicle-fusion-reactor-6"				,"shinybob-bob-vehicleequipment-2"	,"a6"},

						{"vehicle-fusion-cell-1"					,"shinybob-bob-vehicleequipment-3"	,"a1"},
						{"vehicle-fusion-cell-2"					,"shinybob-bob-vehicleequipment-3"	,"a2"},
						{"vehicle-fusion-cell-3"					,"shinybob-bob-vehicleequipment-3"	,"a3"},
						{"vehicle-fusion-cell-4"					,"shinybob-bob-vehicleequipment-3"	,"a4"},
						{"vehicle-fusion-cell-5"					,"shinybob-bob-vehicleequipment-3"	,"a5"},
						{"vehicle-fusion-cell-6"					,"shinybob-bob-vehicleequipment-3"	,"a6"},

						{"vehicle-battery-1"					,"shinybob-bob-vehicleequipment-4"	,"a1"},
						{"vehicle-battery-2"					,"shinybob-bob-vehicleequipment-4"	,"a2"},
						{"vehicle-battery-3"					,"shinybob-bob-vehicleequipment-4"	,"a3"},
						{"vehicle-battery-4"					,"shinybob-bob-vehicleequipment-4"	,"a4"},
						{"vehicle-battery-5"					,"shinybob-bob-vehicleequipment-4"	,"a5"},
						{"vehicle-battery-6"					,"shinybob-bob-vehicleequipment-4"	,"a6"},

						{"vehicle-laser-defense-1"				,"shinybob-bob-vehicleequipment-5"	,"a1"},
						{"vehicle-laser-defense-2"				,"shinybob-bob-vehicleequipment-5"	,"a2"},
						{"vehicle-laser-defense-3"				,"shinybob-bob-vehicleequipment-5"	,"a3"},
						{"vehicle-laser-defense-4"				,"shinybob-bob-vehicleequipment-5"	,"a4"},
						{"vehicle-laser-defense-5"				,"shinybob-bob-vehicleequipment-5"	,"a5"},
						{"vehicle-laser-defense-6"				,"shinybob-bob-vehicleequipment-5"	,"a6"},

						{"vehicle-big-turret-1"					,"shinybob-bob-vehicleequipment-6"	,"a1"},
						{"vehicle-big-turret-2"					,"shinybob-bob-vehicleequipment-6"	,"a2"},
						{"vehicle-big-turret-3"					,"shinybob-bob-vehicleequipment-6"	,"a3"},
						{"vehicle-big-turret-4"					,"shinybob-bob-vehicleequipment-6"	,"a4"},
						{"vehicle-big-turret-5"					,"shinybob-bob-vehicleequipment-6"	,"a5"},
						{"vehicle-big-turret-6"					,"shinybob-bob-vehicleequipment-6"	,"a6"},

						{"vehicle-shield-1"						,"shinybob-bob-vehicleequipment-7"	,"a1"},
						{"vehicle-shield-2"						,"shinybob-bob-vehicleequipment-7"	,"a2"},
						{"vehicle-shield-3"						,"shinybob-bob-vehicleequipment-7"	,"a3"},
						{"vehicle-shield-4"						,"shinybob-bob-vehicleequipment-7"	,"a4"},
						{"vehicle-shield-5"						,"shinybob-bob-vehicleequipment-7"	,"a5"},
						{"vehicle-shield-6"						,"shinybob-bob-vehicleequipment-7"	,"a6"},

						{"vehicle-motor"						,"shinybob-bob-vehicleequipment-8"	,"a1"},
						{"vehicle-engine"						,"shinybob-bob-vehicleequipment-8"	,"a2"},
						{"vehicle-roboport"						,"shinybob-bob-vehicleequipment-8"	,"a3"},
						{"vehicle-roboport-2"					,"shinybob-bob-vehicleequipment-8"	,"a4"},
						},

---=====================
	gemsores = {


						{"ruby-ore"							,"shinybob-oregems"				,"a1"},
						{"sapphire-ore"						,"shinybob-oregems"				,"a2"},
						{"emerald-ore"							,"shinybob-oregems"				,"a3"},
						{"amethyst-ore"						,"shinybob-oregems"				,"a4"},
						{"topaz-ore"							,"shinybob-oregems"				,"a5"},
						{"diamond-ore"							,"shinybob-oregems"				,"a6"},
						{"gem-ore"							,"shinybob-oregems"				,"a7"},

						{"ruby-3"								,"shinybob-rawgems"				,"a1"},
						{"sapphire-3"							,"shinybob-rawgems"				,"a2"},
						{"emerald-3"							,"shinybob-rawgems"				,"a3"},
						{"amethyst-3"							,"shinybob-rawgems"				,"a4"},
						{"topaz-3"							,"shinybob-rawgems"				,"a5"},
						{"diamond-3"							,"shinybob-rawgems"				,"a6"},

						{"ruby-4"								,"shinybob-cutgems"				,"a1"},
						{"sapphire-4"							,"shinybob-cutgems"				,"a2"},
						{"emerald-4"							,"shinybob-cutgems"				,"a3"},
						{"amethyst-4"							,"shinybob-cutgems"				,"a4"},
						{"topaz-4"							,"shinybob-cutgems"				,"a5"},
						{"diamond-4"							,"shinybob-cutgems"				,"a6"},

						{"ruby-5"								,"shinybob-gems"				,"a1"},
						{"sapphire-5"							,"shinybob-gems"				,"a2"},
						{"emerald-5"							,"shinybob-gems"				,"a3"},
						{"amethyst-5"							,"shinybob-gems"				,"a4"},
						{"topaz-5"							,"shinybob-gems"				,"a5"},
						{"diamond-5"							,"shinybob-gems"				,"a6"},
						},


}


sortall(sortordermenus)