data.raw["item"]["battery"]["icon"] = "__BetterIcons__/graphics/icons/battery.png"
data.raw["item"]["flying-robot-frame"]["icon"] = "__BetterIcons__/graphics/icons/flying-robot-frame.png"
data.raw["item"]["oil-refinery"]["icon"] = "__BetterIcons__/graphics/icons/oil-refinery.png"
data.raw["item"]["roboport"]["icon"] = "__BetterIcons__/graphics/icons/roboport.png"
data.raw["item"]["small-lamp"]["icon"] = "__BetterIcons__/graphics/icons/small-lamp.png"
data.raw["item"]["wood"]["icon"] = "__BetterIcons__/graphics/icons/wood.png"
data.raw["item"]["battery-equipment"]["icon"] = "__BetterIcons__/graphics/icons/battery-equipment.png"
data.raw["item"]["battery-mk2-equipment"]["icon"] = "__BetterIcons__/graphics/icons/battery-mk2-equipment.png"
data.raw["item"]["personal-laser-defense-equipment"]["icon"] = "__BetterIcons__/graphics/icons/personal-laser-defense-equipment.png"
data.raw["item"]["personal-roboport-equipment"]["icon"] = "__BetterIcons__/graphics/icons/personal-roboport-equipment.png"
data.raw["item"]["personal-roboport-mk2-equipment"]["icon"] = "__BetterIcons__/graphics/icons/personal-roboport-mk2-equipment.png"
-- data.raw["blueprint"]["blueprint"]["icon"] = "__BetterIcons__/graphics/icons/blueprint.png"
-- data.raw["deconstruction-item"]["deconstruction-planner"]["icon"] = "__BetterIcons__/graphics/icons/deconstruction-planner.png"
data.raw["capsule"]["grenade"]["icon"] = "__BetterIcons__/graphics/icons/grenade.png"
data.raw["capsule"]["cluster-grenade"]["icon"] = "__BetterIcons__/graphics/icons/cluster-grenade.png"
data.raw["capsule"]["poison-capsule"]["icon"] = "__BetterIcons__/graphics/icons/poison-capsule.png"
data.raw["capsule"]["slowdown-capsule"]["icon"] = "__BetterIcons__/graphics/icons/slowdown-capsule.png"
data.raw["projectile"]["grenade"]["animation"]["filename"] = "__BetterIcons__/graphics/icons/grenade.png"
data.raw["projectile"]["cluster-grenade"]["animation"]["filename"] = "__BetterIcons__/graphics/icons/cluster-grenade.png"
data.raw["projectile"]["poison-capsule"]["animation"]["filename"] = "__BetterIcons__/graphics/icons/poison-capsule.png"
data.raw["projectile"]["slowdown-capsule"]["animation"]["filename"] = "__BetterIcons__/graphics/icons/slowdown-capsule.png"
data.raw["recipe"]["basic-oil-processing"]["icon"] = "__BetterIcons__/graphics/icons/basic-oil-processing.png"
data.raw["recipe"]["advanced-oil-processing"]["icon"] = "__BetterIcons__/graphics/icons/advanced-oil-processing.png"
data.raw["recipe"]["coal-liquefaction"]["icon"] = "__BetterIcons__/graphics/icons/coal-liquefaction.png"

data.raw["battery-equipment"]["battery-equipment"]["sprite"]["filename"] = "__BetterIcons__/graphics/equipment/battery-equipment.png"
data.raw["battery-equipment"]["battery-mk2-equipment"]["sprite"]["filename"] = "__BetterIcons__/graphics/equipment/battery-mk2-equipment.png"

data.raw["item"]["solid-fuel"]["icon"] = "__BetterIcons__/graphics/icons/solid-fuel.png"
data.raw["recipe"]["solid-fuel-from-light-oil"]["icon"] = "__BetterIcons__/graphics/icons/solid-fuel-from-light-oil.png"
data.raw["recipe"]["solid-fuel-from-petroleum-gas"]["icon"] = "__BetterIcons__/graphics/icons/solid-fuel-from-petroleum-gas.png"
data.raw["recipe"]["solid-fuel-from-heavy-oil"]["icon"] = "__BetterIcons__/graphics/icons/solid-fuel-from-heavy-oil.png"

data.raw["utility-sprites"]["default"]["show_logistics_network_in_map_view"]["filename"] = "__BetterIcons__/graphics/core-graphics/show-logistics-network-in-map-view.png"
data.raw["utility-sprites"]["default"]["show_pollution_in_map_view"]["filename"] = "__BetterIcons__/graphics/core-graphics/show-pollution-in-map-view.png"
data.raw["utility-sprites"]["default"]["slot_icon_robot"]["filename"] = "__BetterIcons__/graphics/core-graphics/slot-icon-robot.png"
